#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --array=1-20
#SBATCH --mem=2G
#SBATCH --output=converter_array_job_%A_%a.out

rm *.out
config=./config

domain_name=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $2}' $config)

echo ${domain_name}

srun singularity exec --writable-tmpfs --env-file .env-converter --env PATH_DST=/app/exec/data/output/${domain_name} \
 --env DOMAIN_NAME=${domain_name} --env PATH_TMP=/app/exec/data/tmp \
 --bind ./converter:/app/exec/data,\
/g100_work/IscrC_IT-WATER/data_CMCC/reanalysis/:/app/exec/data/input,\
/g100_work/IscrC_IT-WATER/S3M_converter_logs/:/app/exec/data/logs,\
/g100_work/IscrC_IT-WATER/S3M_input/:/app/exec/data/output\
 converter.sif /app/shybox/workflow/converter/launcher.sh